// <auto-generated />
namespace FA.JustBlog.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class nochange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nochange));
        
        string IMigrationMetadata.Id
        {
            get { return "202003110149303_no change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
